[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "rf104",email = "kingaref13@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "vecs (>=0.4.5,<0.5.0)",
    "sentence-transformers (>=5.0.0,<6.0.0)",
    "matplotlib (>=3.10.5,<4.0.0)",
    "Pillow (>=10.0.0,<11.0.0)",
    "python-dotenv (>=1.0.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
seed = "image_search.main:seed"
search = "image_search.main:search"